version: '3.6'

services:
  mongodb-honey:
    image: mongo:4.2.3-bionic
    container_name: mongodb-honey
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=honey
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - honey_net

  rabbitmq-honey:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-honey
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - honey_net

  minio-honey:
    image: minio/minio
    container_name: minio-honey
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: buidat
      MINIO_ROOT_PASSWORD: buitiendat
    command: server --console-address ":9001" /data

  redis-honey:
    image: redis/redis-stack:latest
    container_name: redis-honey
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=buidat
      - REDIS_PORT=6379

  emqx1-emqx:
    image: emqx:5.3.0
    container_name: emqx1-emqx
    environment:
      - 'EMQX_NODE_NAME=emqx@node1.emqx.io'
      - 'EMQX_CLUSTER__DISCOVERY_STRATEGY=static'
      - 'EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]'
    healthcheck:
      test: ['CMD', '/opt/emqx/bin/emqx', 'ctl', 'status']
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
          - node1.emqx.io
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083

  emqx2-honey:
    image: emqx:5.3.0
    container_name: emqx2-honey
    environment:
      - 'EMQX_NODE_NAME=emqx@node2.emqx.io'
      - 'EMQX_CLUSTER__DISCOVERY_STRATEGY=static'
      - 'EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]'
    healthcheck:
      test: ['CMD', '/opt/emqx/bin/emqx', 'ctl', 'status']
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
          - node2.emqx.io

volumes:
  mongodb: {}
  mongoconfig: {}
  minio_storage: {}

networks:
  honey_net:
    driver: bridge
  emqx-bridge:
    driver: bridge
