export enum FEATURE {
  SWIPE = 'SWIPE',
  RANDOM_CHAT = 'RANDOM_CHAT',
  RANDOM_VOICE_CALL = 'RANDOM_VOICE_CALL',
  RANDOM_VIDEO_CALL = 'RANDOM_VIDEO_CALL',
  SPEED_UP = 'SPEED_UP',
  WATCH_HIDE_LIKED = 'WATCH_HIDE_LIKED',
  CUSTOM_LOCATION = 'CUSTOM_LOCATION',
}
