export enum TYPE_MATCH_MAKING {
  RANDOM_CHAT = 'RANDOM_CHAT',
  RANDOM_VOICE_CALL = 'RANDOM_VOICE_CALL',
}

export enum MATCH_MAKING_REQUEST_STATUS {
  PENDING = 'PENDING',
  CONSUMING = 'CONSUMING',
  CONSUMED = 'CONSUMED',
}
