export enum NOTIFICATION_STATUS {
  PENDING = 'pending',
  ERROR = 'error',
  SENT = 'sent',
}

export enum NOTIFICATION_USECASE_TYPE {
  SMS_OTP_REGISTER = 'SMS_OTP_REGISTER',
  SMS_OTP_LOGIN = 'SMS_OTP_LOGIN',
  MAIL_ONBOARD_PENDING = 'MAIL_ONBOARD_PENDING',
  MAIL_MKT_LOYALTY_COIN = 'MAIL_MKT_LOYALTY_COIN',
  MAIL_NEW_MATCH = 'MAIL_NEW_MATCH',
  MAIL_NEW_MESSAGE = 'MAIL_NEW_MESSAGE',
  NOTI_APP_NEW_MATCH = 'NOTI_APP_NEW_MATCH',
  NOTI_APP_NEW_MESSAGE = 'NOTI_APP_NEW_MESSAGE',
  NOTI_APP_MKT_LOYALTY_COIN = 'NOTI_APP_MKT_LOYALTY_COIN',
}
