import { FEATURE } from '@frameworks/data-servies/mongodb/constant/feature.constant'
import { SUBSCRIPTION_TYPE } from '@frameworks/data-servies/mongodb/constant/subscription.constant'
import { TYPE_TRANSACTION } from '@frameworks/data-servies/mongodb/constant/transaction.constant'

export const FEATURE_TO_COIN = {
  [FEATURE.SWIPE]: 1,
  [FEATURE.RANDOM_CHAT]: 2,
  [FEATURE.RANDOM_VOICE_CALL]: 2,
  [FEATURE.RANDOM_VIDEO_CALL]: 4,
  [FEATURE.SPEED_UP]: 3,
  [FEATURE.WATCH_HIDE_LIKED]: 4,
  [FEATURE.CUSTOM_LOCATION]: 3,
}

export enum SUBSCRIPTION_DURATION {
  ONE_MONTH = '1month',
  SIX_MONTH = '6month',
  ONE_YEAR = '1year',
}

export const SUBSCRIPTION_TO_COIN = {
  [SUBSCRIPTION_TYPE.PLUS]: {
    [SUBSCRIPTION_DURATION.ONE_MONTH]: 10,
    [SUBSCRIPTION_DURATION.SIX_MONTH]: 30,
    [SUBSCRIPTION_DURATION.ONE_YEAR]: 40,
    FEATURES: [FEATURE.SWIPE, FEATURE.RANDOM_CHAT, FEATURE.SPEED_UP, FEATURE.CUSTOM_LOCATION],
  },
  [SUBSCRIPTION_TYPE.PREMIUM]: {
    [SUBSCRIPTION_DURATION.ONE_MONTH]: 15,
    [SUBSCRIPTION_DURATION.SIX_MONTH]: 35,
    [SUBSCRIPTION_DURATION.ONE_YEAR]: 50,
    FEATURES: [
      FEATURE.SWIPE,
      FEATURE.RANDOM_CHAT,
      FEATURE.SPEED_UP,
      FEATURE.CUSTOM_LOCATION,
      FEATURE.RANDOM_VOICE_CALL,
      FEATURE.RANDOM_VIDEO_CALL,
      FEATURE.WATCH_HIDE_LIKED,
    ],
  },
}

export const TYPE_SUBSCRIPTION_AND_FEATURE_TO_TRANSACTION = {
  [SUBSCRIPTION_TYPE.PLUS]: TYPE_TRANSACTION.BUI_PLUS,
  [SUBSCRIPTION_TYPE.PREMIUM]: TYPE_TRANSACTION.BUY_PREMIUM,
  [FEATURE.SWIPE]: TYPE_TRANSACTION.BUY_FEATURE_SWIPE,
  [FEATURE.RANDOM_CHAT]: TYPE_TRANSACTION.BUY_FEATURE_RANDOM_CHAT,
  [FEATURE.RANDOM_VOICE_CALL]: TYPE_TRANSACTION.BUY_FEATURE_RANDOM_VOICE,
  [FEATURE.RANDOM_VIDEO_CALL]: TYPE_TRANSACTION.BUY_FEATURE_RANDOM_VIDEO,
  [FEATURE.SPEED_UP]: TYPE_TRANSACTION.BUY_FEATURE_SPEED_UP,
  [FEATURE.WATCH_HIDE_LIKED]: TYPE_TRANSACTION.BUY_FEATURE_WATCH_HIDE_LIKED,
}

export const SUBSCRIPTION_LEVEL = {
  [SUBSCRIPTION_TYPE.PLUS]: 1,
  [SUBSCRIPTION_TYPE.PREMIUM]: 2,
}
