export enum TOKEN_TYPE {
  ACCESS_TOKEN_ONBOARD = 'ACCESS_TOKEN_ONBOARD',
  REFRESH_TOKEN_ONBOARD = 'REFRESH_TOKEN_ONBOARD',
  ACCESS_TOKEN = 'ACCESS_TOKEN',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
}

export const IS_PUBLIC_KEY = 'isPublic'
export const IS_ONBOARD_PENDING_KEY = 'isOnboardPending'
