export const FIRST_MAX_COMPLAINT = 20
export const SECOND_MAX_COMPLAINT = 50
export const THIRD_MAX_COMPLAINT = 150
export const FIRST_MAX_COMPLAINT_PENALTY = 30
export const SECOND_MAX_COMPLAINT_PENALTY = 90
export const THIRD_MAX_COMPLAINT_PENALTY = 360
